prompt: |
        Задача
        Проанализируй расшифровку телефонного разговора и определи, относится ли он к потенциально целевым (B2B) звонкам с интересом к сувенирной продукции. Дай ответ строго одним словом: «да» или «нет». Без комментариев, пояснений и знаков преминаний.
        Контекст 
        Мы — компания «РОССУВЕНИР», работаем только в B2B-сегменте и занимаемся производством и поставкой сувенирной продукции, бизнес-подарков для клиентов, сотрудников и партнёров, а также рекламного мерча (любые товары с нанесением логотипа). Минимальный заказ или конкретные ограничения по объёму роли не играют: важно лишь, что собеседник относится к организации, способной приобретать сувенирную продукцию.
        Возможные роли в разговоре
        Нас интересуют только звонки, в которых участвуют: «Менеджер компании РОССУВЕНИР» и «Клиент» (представитель другой компании, который потенциально может заказывать или уже заказывал сувенирную продукцию).
        Если в звонке участвуют другие люди (другие менеджеры, поставщики, коллеги по внутрикорпоративным вопросам, личные контакты и пр.) и не фигурирует потенциальный клиент из другой компании, это нецелевой звонок.
        Типичные фразы менеджеров компании «РОССУВЕНИР»
        Приветствие и представление компании
        «Здравствуйте, компания РОССУВЕНИР, меня зовут …, чем могу помочь?»
        «Добрый день, вы позвонили в компанию РОССУВЕНИР. Менеджер (Имя), слушаю вас.»
        «Компания РОССУВЕНИР, отдел продаж, здравствуйте.»
        Уточнение потребностей/задачи клиента
        «Подскажите, пожалуйста, какой именно товар вас интересует?»
        «Скажите, в каком объёме вы планируете закупить сувенирную продукцию?»
        «Могу я уточнить, для каких целей вы ищете сувениры?»
        Рассылка предложений, каталогов, коммерческих
        «Могу выслать на вашу почту наш каталог и актуальный прайс.»
        «Пришлите, пожалуйста, ваш адрес электронной почты для отправки коммерческого предложения.»
        «У нас есть большой выбор корпоративных подарков, готов выслать вам несколько вариантов.»
        Обсуждение цен, скидок, условий
        «Сейчас у нас действуют специальные цены, давайте уточним ваш бюджет, чтобы предложить оптимальный вариант.»
        «При заказе от (объём/сумма) мы можем предложить дополнительную скидку.»
        «Обычно мы предоставляем скидку постоянным клиентам или при крупных заказах.»
        Организационные моменты (счёт, договор, отгрузка)
        «Для выставления счёта мне нужны реквизиты вашей компании.»
        «Оплата возможна как по безналичному расчёту, так и наличными при самовывозе.»
        «Сроки изготовления и поставки – (количество) рабочих дней после утверждения макета.»
        Заключение разговора
        «Спасибо за обращение в РОССУВЕНИР, будем рады сотрудничать.»
        «Если у вас останутся вопросы, вы можете позвонить нам или написать на почту.»
        «Отправляю вам всё на почту прямо сейчас, ожидайте, пожалуйста.»

        Типичные фразы клиентов
        Приветствие и/или описание задачи
        «Здравствуйте, меня интересует сувенирная продукция для наших партнёров.»
        «Добрый день, подскажите, пожалуйста, по корпоративным подаркам.»
        «Алло, это РОССУВЕНИР? Хотел бы узнать по поводу подарков…»
        Уточнение ассортимента и наличия
        «Какие варианты подарков у вас есть в наличии?»
        «Можете предложить что-то в определённом ценовом диапазоне?»
        «А есть ли у вас символика [конкретной тематики] или возможность брендирования?»
        Вопросы по цене, срокам, скидкам
        «Сколько будет стоить заказ на (количество) штук?»
        «Нам нужно получить товар срочно; какие сроки доставки вы можете предложить?»
        Обсуждение макетов/брендинга
        «Можем ли мы нанести наш логотип на продукцию?»
        «У нас есть готовый дизайн, куда его лучше отправить?»
        «Смогут ли ваши дизайнеры помочь с доработкой макета?»
        Завершение разговора
        «Спасибо, я подумаю и свяжусь с вами позже.»
        «Хорошо, жду от вас счёт и подтверждение по наличию.»
        Шумы и неинформативные фразы
        Игнорируй слова-паразиты, паузы («мм», «э-э», «ага») и фразы, которые не несут смысловой нагрузки.
        Критерии для ответа «да»
        Звонок действительно между нашим менеджером и представителем другой компании (B2B).
        Собеседник либо уже покупал/покупает сувенирную продукцию, либо проявляет/может проявить интерес к ней (задаёт вопросы, запрашивает детали, готов обсудить покупку).
        Достаточно одного чёткого признака (упоминание заказа, интерес к товарам, запрос прайса или каталога и т. п.), чтобы ответить «да».
        Критерии для ответа «нет»
        Если разговор не между «Менеджером РОССУВЕНИР» и «Клиентом» (например, внутрикорпоративные переговоры, разговор с поставщиком и т. д.).
        Если в разговоре нет признаков интереса к сувенирной продукции, нет упоминания о возможной покупке или потребности.
        Если собеседник явно говорит, что им это неинтересно или это не их профиль.
        Если недостаточно данных, чтобы определить B2B-контакт или интерес (разговор слишком краткий, оборванный, не по теме и т. п.).
        Ответ
        Дай ровно одно слово без знаков препинания, комментариев и пояснений: либо «ДА», либо «НЕТ».
        «ДА» – если разговор соответствует критериям потенциального клиента (B2B и есть интерес).
        «НЕТ» – во всех остальных случаях.
        Примеры
        Пример «да»
        Менеджер: «Здравствуйте, компания РОССУВЕНИР…»
        Клиент: «Добрый день, мы ищем сувениры к годовщине фирмы, подскажите, что у вас есть?»
        Результат: «ДА»
        Пример «нет»
        Менеджер: «Здравствуйте, компания РОССУВЕНИР…»
        Собеседник: «Я из транспортной компании, нам не нужна сувенирная продукция, мы занимаемся перевозками, извините…»
        Результат: «НЕТ»




yes_duration: 300
company_counts_limit: all

transcrib_model: medium
fp16: true
device: cuda
